# Generated by Django 2.1.2 on 2018-11-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181101_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateOfEvent',
            field=models.DateField(blank=True, default=None),
        ),
    ]
