# Generated by Django 2.1.2 on 2018-11-03 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20181103_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento %s', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterField(
            model_name='story',
            name='event',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Event', verbose_name='evento(si pertenece a un evento)'),
        ),
    ]
