# Generated by Django 2.1.2 on 2018-11-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_event_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithprofile',
            name='writtenStories',
            field=models.ManyToManyField(blank=True, related_name='WrittenStories', to='app.Story', verbose_name='Historias escritas por mi'),
        ),
        migrations.AlterField(
            model_name='userwithprofile',
            name='favoriteStories',
            field=models.ManyToManyField(blank=True, related_name='FavoriteStories', to='app.Story', verbose_name='historias favoritas'),
        ),
    ]
