# Generated by Django 2.1.2 on 2018-11-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20181103_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithprofile',
            name='followedCategories',
            field=models.ManyToManyField(blank=True, to='app.Category', verbose_name='Categorías que sigue'),
        ),
    ]
