# Generated by Django 2.1.2 on 2018-11-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20181104_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithprofile',
            name='profileImage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='userpic_folder/'),
        ),
    ]
