# Generated by Django 2.1.2 on 2018-11-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_userwithprofile_likedstories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='ranking',
            field=models.PositiveIntegerField(default=0, verbose_name='ranking(número de "me gusta")'),
        ),
    ]
