# Generated by Django 2.1.2 on 2018-11-07 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20181106_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoría o Evento', 'verbose_name_plural': 'Categorías o Eventos'},
        ),
    ]
