# Generated by Django 2.1.2 on 2018-11-12 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20181107_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetitionForAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=300, verbose_name='título de la petición')),
                ('message', models.CharField(max_length=10000, verbose_name='descripción de la petición')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.UserWithProfile', verbose_name='autor de la petición')),
            ],
            options={
                'verbose_name': 'Petición de usuario',
                'verbose_name_plural': 'Peticiones de usuario',
            },
        ),
    ]
