# Generated by Django 2.1.2 on 2018-11-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_story_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followedUsers',
            field=models.ManyToManyField(blank=True, to='app.User'),
        ),
    ]
