# Generated by Django 2.1.2 on 2018-11-01 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181101_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=10000)),
                ('dateOfEvent', models.DateField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='dateOfEvent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='isEvent',
        ),
        migrations.AddField(
            model_name='story',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Event'),
        ),
    ]
