# Generated by Django 2.1.2 on 2018-11-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181101_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateOfEvent',
            field=models.DateField(blank=True),
        ),
    ]
