# Generated by Django 2.1.2 on 2018-11-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20181101_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithprofile',
            name='favoriteStories',
            field=models.ManyToManyField(blank=True, to='app.Story'),
        ),
    ]
