# Generated by Django 2.1.2 on 2018-11-03 00:02

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20181102_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=10000, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor del comentario'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(max_length=10000, verbose_name='descripción del comentario'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ranking',
            field=models.IntegerField(default=0, verbose_name='ranking(número de "me gusta")'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Story', verbose_name='historia a la que pertenece'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dateOfEvent',
            field=models.DateField(blank=True, verbose_name='fecha del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=10000, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='story',
            name='event',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.CASCADE, to='app.Event', verbose_name='evento(si pertenece a un evento)'),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='story',
            name='message',
            field=models.CharField(max_length=10000, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='story',
            name='ranking',
            field=models.IntegerField(default=0, verbose_name='ranking(número de "me gusta")'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=300, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='userwithprofile',
            name='biography',
            field=models.CharField(blank=True, max_length=500, verbose_name='biografía'),
        ),
        migrations.AlterField(
            model_name='userwithprofile',
            name='favoriteStories',
            field=models.ManyToManyField(blank=True, to='app.Story', verbose_name='historias favoritas'),
        ),
        migrations.AlterField(
            model_name='userwithprofile',
            name='followedUsers',
            field=models.ManyToManyField(blank=True, to='app.UserWithProfile', verbose_name='usuario que sigue'),
        ),
        migrations.AlterField(
            model_name='userwithprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
