# Generated by Django 2.1.2 on 2018-11-03 19:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20181103_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='color'),
        ),
    ]
