# Generated by Django 2.1.2 on 2018-11-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_userwithprofile_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isEvent',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Es un evento?'),
        ),
    ]
