# Generated by Django 2.1.2 on 2018-11-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20181106_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithprofile',
            name='likedStories',
            field=models.ManyToManyField(blank=True, related_name='LikedStories', to='app.Story', verbose_name='historias que me gustaron'),
        ),
    ]
